export const topics = [
	'REST APIs',
	'Microservices architecture',
	'Event-driven design',
	'Load balancing',
	'Scalability vs Availability',
	'Database indexing',
	'ACID vs BASE',
	'CAP Theorem',
	'Postgres',
	'MongoDB',
	'Redis',
	'NoSQL databases',
	'SQL vs NoSQL',
	'Data structures and algorithms',
	'Big O notation',
	'Linked lists vs arrays',
	'Hash tables',
	'Binary trees',
	'Graph algorithms',
	'Sorting algorithms',
	'Search algorithms',
	'Asynchronous programming',
	'Promises vs Callbacks',
	'Event loop in JavaScript',
	'Node.js vs Deno',
	'Server-side rendering vs Client-side rendering',
	'Progressive enhancement vs Graceful degradation',
	'Single Page Applications (SPA)',
	'Progressive Web Apps (PWA)',
	'Responsive design',
	'Cross-origin resource sharing (CORS)',
	'Web security (CORS, CSRF, XSS)',
	'Authentication methods (Basic, Digest, OAuth)',
	'Authorization methods (RBAC, ABAC)',
	'WebSockets vs HTTP/2',
	'GraphQL vs REST APIs',
	'WebAssembly',
	'Content Delivery Networks (CDN)',
	'Serverless architecture',
	'Microservices vs Monoliths',
	'API versioning strategies',
	'API documentation (OpenAPI, Swagger)',
	'Rate limiting strategies',
	'Caching strategies (HTTP, Redis)',
	'Postman vs Insomnia',
	'API testing tools',
	'Unit testing vs Integration testing',
	'End-to-end testing',
	'Test-driven development (TDD)',
	'Behavior-driven development (BDD)',
	'Continuous Integration (CI)',
	'Continuous Deployment (CD)',
	'Version control systems (Git, Mercurial)',
	'Git branching strategies (Git Flow, GitHub Flow)',
	'Pull requests vs Merge requests',
	'Code reviews best practices',
	'Code quality tools (ESLint, Prettier)',
	'Static code analysis',
	'Dynamic code analysis',
	'Dependency management (npm, yarn)',
	'Semantic versioning',
	'Package-lock.json vs yarn.lock',
	'Monorepo vs Polyrepo',
	'Microservices communication patterns',
	'Message queues (Kafka, RabbitMQ)',
	'Caching strategies',
	'CDNs',
	'OAuth 2.0 and JWT',
	'Service discovery',
	'Rate limiting',
	'Circuit breakers',
	'Node.js event loop',
	'JavaScript closures',
	'Promises and async/await',
	'Memory leaks in JavaScript',
	'Express.js middleware',
	'Dockerfile best practices',
	'Multi-stage Docker builds',
	'Docker volumes vs bind mounts',
	'Kubernetes pods and services',
	'Kubernetes deployments and replicasets',
	'Horizontal pod autoscaling',
	'CI/CD pipelines',
	'Infrastructure as Code (Terraform)',
	'Reverse proxies (Nginx, Traefik)',
	'Monorepos vs Polyrepos',
	'API Gateway patterns',
	'Serverless architecture',
	'WebSockets and real-time communication',
	'Progressive Web Apps (PWA)',
	'TypeScript type system',
	'Package managers (npm, yarn, pnpm)',
	'Semantic versioning',
	'Module bundlers (Webpack, Vite)',
	'Design patterns (Factory, Singleton, Observer)',
	'Container orchestration',
	'DevOps culture and practices',
	'Monitoring and observability',
	'Distributed tracing',
	'Zero downtime deployments',
	'Authentication vs Authorization',
	'GraphQL vs REST',
	'Domain Driven Design (DDD)',
	'Software testing (unit, integration, E2E)',
	'Twelve-Factor App methodology',
];
